### ISSUE TITLE
help with an error from an untalented syntax guy ;)

### ISSUE THREAD

**Issue by n1ete** [felixjung/dotfiles#1]
i get always the following error and i am not be able to fix this, any ideas what went wrong?
`/Users/user/.zsh/.zshrc:12: no matches found: /Users/user/.dotfiles/(^(undo|packages|.zim))#/*.zsh`
thx in advance...

**Comment by n1ete** [comment]
to stupid to notice that my dotfiles folder where on a different folder.... closed and a pile of shame for me xD

**Comment by felixjung** [comment]
All good. Sorry, I couldn't help you earlier.
